# Generated by Django 4.0.3 on 2022-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.PositiveSmallIntegerField(choices=[(0, 'brak'), (1, 'first dept'), (2, 'Second dept')], default=0),
        ),
    ]
